name: Push installation image 

on: 
  workflow_dispatch:
  release:
    types: [published, created, edited]

jobs:
  windows-install-node:
    runs-on: windows-latest

    steps:
      - name: Download node.js version from nodejs.org
        run: |
          curl -o ./nodejs-win.zip --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-win-x64.zip      
          mkdir nodejs-win && tar -xzf nodejs-win.zip -C nodejs-win --strip-components=1 
          rm ./nodejs-win.zip

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: purple-hats

      - name: Copy scripts to parent directory
        run: |
          cp ${{github.workspace}}/purple-hats/scripts/*.ps1 ${{github.workspace}}
          cp ${{github.workspace}}/purple-hats/scripts/*.cmd ${{github.workspace}}      
          rd -r ${{github.workspace}}/purple-hats/scripts

      - name: Run hats_shell._ps.ps1 before installing node modules
        shell: pwsh
        run: powershell.exe -NoProfile -ExecutionPolicy Bypass "& ${{github.workspace}}\hats_shell_ps.ps1" "cd ${{github.workspace}}\purple-hats;npm i fsevents@latest -f --save-optional"     
        working-directory:  ${{github.workspace}}

      - name: Zip entire Purple Hats folder (Windows)
        shell: pwsh
        run: Compress-Archive -Path ${{github.workspace}}/* -DestinationPath purple-hats-portable-windows.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: purple-hats-portable-windows
          path: ./purple-hats-portable-windows.zip

  mac-security-prompt-install-node:
    runs-on: macos-latest  

    steps:
      - name: Download node.js version from nodejs.org
        run: |         
          curl -o ./nodejs-mac-arm64.tar.gz --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-darwin-arm64.tar.gz      
          mkdir nodejs-mac-arm64 && tar -xzf nodejs-mac-arm64.tar.gz -C nodejs-mac-arm64 --strip-components=1 && rm ./nodejs-mac-arm64.tar.gz
          curl -o ./nodejs-mac-x64.tar.gz --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-darwin-x64.tar.gz     
          mkdir nodejs-mac-x64 && tar -xzf nodejs-mac-x64.tar.gz -C nodejs-mac-x64 --strip-components=1 && rm ./nodejs-mac-x64.tar.gz

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: purple-hats

      - name: Install Node Modules for Mac0S
        run: |
          if [[ $(uname -m) == 'arm64' ]]; then
            export PATH_TO_NODE="${{github.workspace}}/nodejs-mac-arm64/bin"
            export PATH="$PATH_TO_NODE:$PATH"
          else
            export PATH_TO_NODE="${{github.workspace}}/nodejs-mac-x64/bin"
            export PATH="$PATH_TO_NODE:$PATH"
          fi
          npm ci 
        working-directory: purple-hats

      - name: Grant execute permissions for user
        run: chmod ugo+rwx ./scripts/hats_shell.command ./scripts/hats_shell.sh ./scripts/purple_hats_install.command
        working-directory: purple-hats

      - name: Copy scripts to parent directory
        run: |
          cp ./purple-hats/scripts/{hats_shell.command,hats_shell.sh,purple_hats_install.command}  ${{ github.workspace }}
          rm -rf ./purple-hats/scripts
      
      - name: Zip entire Purple Hats folder (Mac)
        run: |
          if [[ $(uname -m) == 'arm64' ]]
          then        
            zip purple-hats-portable-mac-arm64.zip -y -r ./ --exclude 'hats_shell_ps.ps1' 'hats_shell.cmd'
          else
            zip purple-hats-portable-mac-x64.zip -y -r ./ --exclude 'hats_shell_ps.ps1' 'hats_shell.cmd'
          fi
      
      - name: Upload Mac artifact
        uses: actions/upload-artifact@v3
        with:
          name: purple-hats-portable-mac
          path: ./purple-hats-portable-mac-*.zip
